config/routes.rb
Rails.application.routes.draw do

  root "lists#index"
  resources :lists do
    member do
      patch :complete
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord

  def done?
    done
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :find_list, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @lists = List.all
    @list = List.new
  end

  def new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path, notice: "新增待辦事項"
    else
      render "new", alert: "新增待辦事項失敗"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @list.update(list_params)
      redirect_to lists_path, notice: "修改待辦事項"
    else
      render "edit", alert: "修改待辦失敗"
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, notice: "刪除待辦事項"
  end

  def complete
    @list.update_attribute(:done , true)
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end

  def find_list
    @list = List.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>

  <body>

    <header id="header">
      <nav class="navbar sticky-top navbar-expand-lg">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto ml-auto">
            <li class="nav-item">
              <%= link_to "My tasks", lists_path, class: "nav-link mr-5" %>
            </li>
            <li class="nav-item">
              <a class="nav-link mr-5" href="#">Link</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="#">Disabled</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do |f| %>
  <%= f.text_field :title, placeholder: "+ ADD Task", class: "form-control form-control-lg" %>
<% end %>

app/views/lists/edit.html.erb
<%= render "form" %>

app/views/lists/index.html.erb
<section id="section_list_index">
  <div class="container">
    <div class="row">

      <div class="col-md-8 offset-md-2">
        <%= render "form" %>

        <% @lists.each do |list| %>
          <div class="card mt-3 mb-3">
            <div class="card-body">
              <div class="row">
                <% if list.done? %>
                  <div class="col-md-2 text-center">
                    <%= link_to complete_list_path(list), method: :patch do %>
                      <i class="fas fa-check-square"></i>
                    <% end %>
                  </div>
                  <div class="col-md-8"><h4 class="card-title text-muted"><del><%= list.title %></del></h4></div>
                  <div class="col-md-2">
                    <i class="far fa-star mr-4"></i>
                    <%= link_to list_path(list) do %>
                      <i class="fas fa-pencil-alt"></i>
                    <% end %>
                  </div>
                <% else %>
                  <div class="col-md-2 text-center">
                    <%= link_to complete_list_path(list), method: :patch do %>
                      <i class="far fa-square"></i>
                    <% end %>
                  </div>
                  <div class="col-md-8"><h4 class="card-title"><%= list.title %></h4></div>
                  <div class="col-md-2">
                    <i class="far fa-star mr-4"></i>
                    <%= link_to list_path(list) do %>
                      <i class="fas fa-pencil-alt"></i>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</section>


<% @lists.each do |list| %>
  <ul>
    <li>
      <%= list.title %>
      <%= link_to "Show", list_path(list) %>
      <%= link_to "Edit", edit_list_path(list) %>
      <%= link_to "Delete", list_path(list), method: :delete, data: {confirm: "Are you sure?"} %>
    </li>
  </ul>
<% end %>

app/views/lists/new.html.erb
<%= render "form" %>

app/views/lists/show.html.erb
<section id="section_list_show">
  <div class="container">
    <div class="row">

      <div class="col-md-8 offset-md-2">
        <%#= render "form" %>

        <div class="card mt-3 mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-md-2 text-center">
                <i class="far fa-square"></i>
              </div>
              <div class="col-md-8"><h4 class="card-title"><%= @list.title %></h4></div>
              <div class="col-md-2">
                <i class="far fa-star mr-4"></i>
                <%= link_to list_path(@list) do %>
                  <i class="fas fa-pencil-alt"></i>
                <% end %>
              </div>
            </div>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Vestibulum at eros</li>
          </ul>
        </div>

      </div>

    </div>
  </div>
</section>